load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "AttributeGenerator",
    srcs = glob([
        "*.swift",
    ]),
    generates_header = True,
    module_name = "AttributeGenerator",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
